### ISSUE TITLE
WebInterface not working on new install with latest v0.16

### ISSUE THREAD

**Issue by dannygee87** [mayanayza/netvisor#590]
Describe the bug
New install on a Debian server via Docker using the quick install commands:

```
Bash
curl -O https://raw.githubusercontent.com/scanopy/scanopy/refs/heads/main/docker-compose.yml
# Changed the external address to the server IP/address
docker compose up -d
```
Symptoms:
The page remains empty (blueish background with favicon).
The browser console shows the following error:
Uncaught (in promise) TypeError: crypto.randomUUID is not a function

Expected behavior
The Scanopy login or dashboard should be visible.

Environment:

Browser: Chrome

Scanopy Version: 0.16

Connection: HTTP (Non-secure context)

Additional context
The issue seems to be related to the requirement of a "Secure Context" for crypto.randomUUID in modern browsers.

Note: Downgrading to server version v0.15.6 works as expected.

After upgrading to v0.16 and setting as unsecure in chrome it works as excpected

[x] I have reviewed [The docs](https://scanopy.net/docs)

Update:
I can confirm that v0.16.0 works as expected after explicitly white-listing the origin in Chrome.

By enabling the flag chrome://flags/#unsafely-treat-insecure-origin-as-secure for my server's IP/port, the frontend loads correctly. This confirms that the issue is the missing Secure Context (HTTP vs. HTTPS) required for crypto.randomUUID in version 0.16.

Since version 0.15.6 worked fine without this, it seems like a new dependency that breaks setups without a Reverse Proxy/SSL.

**Comment by mayanayza** [comment]
This should be fixed in v0.16.1. Please give it a shot and lmk!
